export const WorkoutActionTypes = {
    SET_CURRENT_WORKOUT: "SET_CURRENT_WORKOUT",
    CREATE_CURRENT_WORKOUT_START: "CREATE_CURRENT_WORKOUT_START",
    CREATE_CURRENT_WORKOUT_SUCCESS: "CREATE_CURRENT_WORKOUT_SUCCESS",
    CREATE_CURRENT_WORKOUT_FAIL: "CREATE_CURRENT_WORKOUT_FAIL"
}