export const WorkoutActionTypes = {
    SET_CURRENT_WORKOUT: "SET_CURRENT_WORKOUT",
    CREATE_CURRENT_WORKOUT_START: "CREATE_CURRENT_WORKOUT_START",
    CREATE_CURRENT_WORKOUT_SUCCESS: "CREATE_CURRENT_WORKOUT_SUCCESS",
    CREATE_CURRENT_WORKOUT_FAIL: "CREATE_CURRENT_WORKOUT_FAIL",
    ADD_EXERCISE_START: "ADD_EXERCISE_START",
    ADD_EXERCISE_SUCCESS: "ADD_EXERCISE_SUCCESS",
    ADD_EXERCISE_FAIL: "ADD_EXERCISE_FAIL",
    DELETE_EXERCISE_START: "DELETE_EXERCISE_START",
    DELETE_EXERCISE_SUCCESS: "DELETE_EXERCISE_SUCCESS",
    DELETE_EXERCISE_FAIL: "DELETE_EXERCISE_FAIL",
    SWAP_EXERCISE_START: "SWAP_EXERCISE_START",
    SWAP_EXERCISE_SUCCESS: "SWAP_EXERCISE_SUCCESS",
    SWAP_EXERCISE_FAIL: "SWAP_EXERCISE_FAIL",
    UPDATE_WORKOUT: "UPDATE_WORKOUT"
}