export const LeaderboardActionTypes = {
    FETCH_LEADERBOARD_START: "FETCH_LEADERBOARD_START",
    FETCH_LEADERBOARD_SUCCESS: "FETCH_LEADERBOARD_SUCCESS",
    FETCH_LEADERBOARD_FAIL: "FETCH_LEADERBOARD_FAIL",
}