export const UserActionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_USER_GOALS_START: "SET_USER_GOALS_START",
    SET_USER_GOALS_SUCCESS: "SET_USER_GOALS_SUCCESS",
    SET_USER_GOALS_FAIL: "SET_USER_GOALS_FAIL",
    SET_SPLIT_TYPE_START: "SET_SPLIT_TYPE_START",
    SET_SPLIT_TYPE_SUCCESS: "SET_SPLIT_TYPE_SUCCESS",
    SET_SPLIT_TYPE_FAIL: "SET_USER_GOALS_FAIL"
}