export const UserActionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_USER_GOALS_START: "SET_USER_GOALS_START",
    SET_USER_GOALS_SUCCESS: "SET_USER_GOALS_SUCCESS",
    SET_USER_GOALS_FAIL: "SET_USER_GOALS_FAIL",
    SET_PROFILE_SETTINGS_START: "SET_PROFILE_SETTINGS_START",
    SET_PROFILE_SETTINGS_SUCCESS: "SET_PROFILE_SETTINGS_SUCCESS",
    SET_PROFILE_SETTINGS_FAIL: "SET_PROFILE_SETTINGS_FAIL"
}