export const WorkoutsActionTypes = {
    FETCH_WORKOUTS_START: "FETCH_WORKOUTS_START",
    FETCH_WORKOUTS_SUCCESS: "FETCH_WORKOUTS_SUCCESS",
    FETCH_WORKOUTS_FAIL: "FETCH_WORKOUTS_FAIL",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    DELETE_WORKOUT_START: "DELETE_WORKOUT_START",
    DELETE_WORKOUT_SUCCESS: "DELETE_WORKOUT_SUCCESS",
    DELETE_WORKOUT_FAIL: "DELETE_WORKOUT_FAIL",
}